name: Coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Coverage
      run: |
        npm ci
        npm run test-cov

  setstatus:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Custom Github Status
      uses: geekodour/gh-actions-custom-status@v0.0.4
      with:
          args: >-
            --state=success
